[default]
EXTENSIONS = [
  "templateapi.extensions.commands",
  "templateapi.extensions.database",
  "templateapi.blueprints.restapi",
]
SQLALCHEMY_DATABASE_URI = "sqlite:///database///test.db"
TITLE = "TemplateApi"

[production]
SQLALCHEMY_DATABASE_URI = "sqlite:///prodtest.db"
