[default]
EXTENSIONS = [
  "extensions.database",
  "blueprints.restapi",
]
SQLALCHEMY_DATABASE_URI = "sqlite:///test.db"
TITLE = "TemplateApi"

[production]
SQLALCHEMY_DATABASE_URI = "sqlite:///prodtest.db"
